const roles = [
  {
    roleName: 'operator',
    operateRole: ['PRESCRIPTION_READ', 'ORGANIZATION_DEPARTMENT_READ', 'DOCTOR_READ', 'DOCTOR_DOWNLOAD', 'NURSE_READ', 'NURSE_DOWNLOAD', 'ACTIVITY_READ', 'COUPON_READ', 'COUPON_UPDATE', 'COUPON_DELETE', 'COUPON_DOWNLOAD', 'CAROUSEL_CREATE', 'CAROUSEL_READ', 'CAROUSEL_UPDATE', 'CAROUSEL_DELETE', 'MEDICAL_ASSISTANT_CREATE', 'MEDICAL_ASSISTANT_READ', 'MEDICAL_ASSISTANT_UPDATE', 'MEDICAL_ASSISTANT_EXPORT', 'MEDICAL_ASSISTANT_DOWNLOAD', 'EVALUATE_READ'],
    navigateRole: ['ORDER', 'OVERVIEW', 'INTERROGATION', 'PRESCRIPTION', 'REFUND', 'MASTER_DATA', 'ORGANIZATION_DEPARTMENT', 'DOCTOR', 'NURSE', 'EVALUATE'],
  }, {
    roleName: 'outpatient_department_admin',
    operateRole: ['INTERROGATION_EXPORT', 'INTERROGATION_READ', 'PRESCRIPTION_EXPORT', 'PRESCRIPTION_READ', 'HOSPITAL_READ', 'HOSPITAL_UPDATE', 'DEPARTMENT_READ', 'DOCTOR_READ', 'DOCTOR_UPDATE', 'DOCTOR_DOWNLOAD', 'NURSE_READ', 'NURSE_UPDATE', 'NURSE_DOWNLOAD', 'ACTIVITY_CREATE', 'ACTIVITY_READ', 'ACTIVITY_UPDATE', 'COUPON_DOWNLOAD', 'EVALUATE_READ', 'EVALUATE_EXAMINE', 'SCHEDULE_READ', 'SCHEDULE_CREATE'],
    navigateRole: ['ORDER', 'OVERVIEW', 'INTERROGATION', 'PRESCRIPTION', 'REFUND', 'MASTER_DATA', 'HOSPITAL', 'DEPARTMENT', 'DOCTOR', 'NURSE', 'ACTIVITY_ACTIVITY', 'COUPON', 'EVALUATE', 'SCHEDULE', 'MEDICAL', 'DATA_STATISTICS'],
  }, {
    roleName: 'information_department_admin',
    operateRole: ['INTERROGATION_EXPORT', 'INTERROGATION_READ', 'HOSPITAL_READ', 'HOSPITAL_UPDATE', 'DEPARTMENT_READ', 'ORGANIZATION_DEPARTMENT_CREATE', 'ORGANIZATION_DEPARTMENT_READ', 'ORGANIZATION_DEPARTMENT_UPDATE', 'ORGANIZATION_DEPARTMENT_DELETE', 'DOCTOR_READ', 'DOCTOR_UPDATE', 'DOCTOR_CREATE', 'DOCTOR_DOWNLOAD', 'NURSE_READ', 'NURSE_UPDATE', 'NURSE_CREATE', 'NURSE_DOWNLOAD', 'ACTIVITY_READ', 'COUPON_READ', 'COUPON_DOWNLOAD', 'EVALUATE_READ', 'SCHEDULE_READ', 'SCHEDULE_CREATE', 'MEDICAL_READ'],
    navigateRole: ['ORDER', 'OVERVIEW', 'INTERROGATION', 'REFUND', 'MASTER_DATA', 'HOSPITAL', 'DEPARTMENT', 'ORGANIZATION_DEPARTMENT', 'DOCTOR', 'NURSE', 'ACTIVITY_ACTIVITY', 'COUPON', 'EVALUATE', 'SCHEDULE', 'MEDICAL', 'DATA_STATISTICS'],
  }, {
    roleName: 'pharmacy_department',
    operateRole: ['PRESCRIPTION_EXPORT', 'PRESCRIPTION_READ', 'MEDICAL_READ'],
    navigateRole: ['ORDER', 'PRESCRIPTION', 'MASTER_DATA', 'DEPARTMENT', 'MEDICAL', 'DATA_STATISTICS']
  }, {
    roleName: 'propaganda_department_admin',
    operateRole: ['HOSPITAL_READ', 'HOSPITAL_UPDATE', 'DOCTOR_DOWNLOAD', 'NURSE_DOWNLOAD', 'ACTIVITY_CREATE', 'ACTIVITY_READ', 'ACTIVITY_UPDATE', 'COUPON_CREATE', 'COUPON_DELETE', 'COUPON_UPDATE', 'COUPON_DOWNLOAD', 'CAROUSEL_CREATE', 'CAROUSEL_READ', 'CAROUSEL_UPDATE', 'CAROUSEL_DELETE'],
    navigateRole: ['MASTER_DATA', 'HOSPITAL', 'DEPARTMENT', 'DOCTOR', 'NURSE', 'ACTIVITY_ACTIVITY', 'COUPON', 'CAROUSEL']
  }, {
    roleName: 'finance_department_admin',
    operateRole: ['OVERVIEW_EXPORT', 'INTERROGATION_EXPORT', 'REFUND_EXPORT', 'DEPARTMENT_READ', 'ORGANIZATION_DEPARTMENT_READ' ,'DOCTOR_READ', 'DOCTOR_UPDATE', 'DOCTOR_DOWNLOAD', 'NURSE_READ', 'ACTIVITY_READ', 'COUPON_READ', 'COUPON_DOWNLOAD', 'SCHEDULE_READ'],
    navigateRole: ['ORDER', 'OVERVIEW', 'INTERROGATION', 'REFUND', 'MASTER_DATA', 'DEPARTMENT', 'ORGANIZATION_DEPARTMENT', 'DOCTOR', 'NURSE', 'ACTIVITY_ACTIVITY', 'COUPON', 'SCHEDULE', 'DATA_STATISTICS']
  }, {
    roleName: 'medical_department_admin',
    operateRole: ['INTERROGATION_EXPORT', 'INTERROGATION_READ', 'PRESCRIPTION_READ', 'HOSPITAL_READ', 'DEPARTMENT_READ', 'ORGANIZATION_DEPARTMENT_READ', 'DOCTOR_READ', 'DOCTOR_UPDATE', 'DOCTOR_DELETE', 'DOCTOR_CREATE', 'DOCTOR_DOWNLOAD', 'NURSE_READ', 'NURSE_UPDATE', 'NURSE_DELETE', 'NURSE_CREATE', 'NURSE_DOWNLOAD', 'ACTIVITY_READ', 'COUPON_READ', 'COUPON_DOWNLOAD', 'EVALUATE_READ', 'SCHEDULE_READ'],
    navigateRole: ['ORDER', 'OVERVIEW', 'INTERROGATION', 'PRESCRIPTION', 'MASTER_DATA', 'HOSPITAL', 'DEPARTMENT', 'ORGANIZATION_DEPARTMENT', 'DOCTOR', 'NURSE', 'ACTIVITY_ACTIVITY', 'COUPON', 'EVALUATE', 'SCHEDULE', 'DATA_STATISTICS']
  }, {
    roleName: 'uma_protection',
    operateRole: [],
    navigateRole: [],
  }
];

export default {
  canIVisit (role, type, functions) {
    if (role === 'admin') {
      return true;
    }
    if ((role === 'hospital_admin') && (functions !== 'DEPARTMENT') && (functions !== 'OPERATE')  && (functions !== 'MEDICAL_READ')  && (functions !== 'MEDICAL_EXPORT') && (functions !== 'HOSPITAL_CREATE') && (functions !== 'HOSPITAL_DELETE') && (functions !== 'ACTIVITY') && (functions !== 'CAROUSEL') && (functions !== 'DATA_STATISTICS')) {
      return true;
    }
    role = roles.find(r => r.roleName === role);
    if (role && role[`${type}Role`].find(item => item === functions)) {
      return true;
    }
    return false;
  }
}
